INSERT INTO skladnik(name) VALUES ('broccoli floret');
INSERT INTO skladnik(name) VALUES ('dried sweet basil leaves');
INSERT INTO skladnik(name) VALUES ('strawberry');
INSERT INTO skladnik(name) VALUES ('onion');
INSERT INTO skladnik(name) VALUES ('turkey');
INSERT INTO skladnik(name) VALUES ('fresh garlic');
INSERT INTO skladnik(name) VALUES ('frozen french fries');
INSERT INTO skladnik(name) VALUES ('pepper');
INSERT INTO skladnik(name) VALUES ('ciabatta');
INSERT INTO skladnik(name) VALUES ('whole berry cranberry sauce');
INSERT INTO skladnik(name) VALUES ('gingerroot');
INSERT INTO skladnik(name) VALUES ('half-and-half');
INSERT INTO skladnik(name) VALUES ('lemon juice');
INSERT INTO skladnik(name) VALUES ('fresh tomato');
INSERT INTO skladnik(name) VALUES ('ground black pepper');
INSERT INTO skladnik(name) VALUES ('ground coriander');
INSERT INTO skladnik(name) VALUES ('red pepper flakes');
INSERT INTO skladnik(name) VALUES ('salt & fresh ground pepper');
INSERT INTO skladnik(name) VALUES ('herbs');
INSERT INTO skladnik(name) VALUES ('red cinnamon candies');
INSERT INTO skladnik(name) VALUES ('chicken rice soup');
INSERT INTO skladnik(name) VALUES ('rice vinegar');
INSERT INTO skladnik(name) VALUES ('red chile');
INSERT INTO skladnik(name) VALUES ('lean pork chops');
INSERT INTO skladnik(name) VALUES ('water chestnut');
INSERT INTO skladnik(name) VALUES ('good seasonings italian salad dressing mix');
INSERT INTO skladnik(name) VALUES ('white kidney beans');
INSERT INTO skladnik(name) VALUES ('bean sprouts');
INSERT INTO skladnik(name) VALUES ('mustard');
INSERT INTO skladnik(name) VALUES ('light soy sauce');
INSERT INTO skladnik(name) VALUES ('whipped cream');
INSERT INTO skladnik(name) VALUES ('baking powder');
INSERT INTO skladnik(name) VALUES ('white wine');
INSERT INTO skladnik(name) VALUES ('cayenne');
INSERT INTO skladnik(name) VALUES ('whole wheat bread dough');
INSERT INTO skladnik(name) VALUES ('cayenne pepper');
INSERT INTO skladnik(name) VALUES ('frozen juice concentrate');
INSERT INTO skladnik(name) VALUES ('cinnamon');
INSERT INTO skladnik(name) VALUES ('corn oil');
INSERT INTO skladnik(name) VALUES ('egg');
INSERT INTO skladnik(name) VALUES ('chinese noodles');
INSERT INTO skladnik(name) VALUES ('banana');
INSERT INTO skladnik(name) VALUES ('tomato sauce');
INSERT INTO skladnik(name) VALUES ('black cumin');
INSERT INTO skladnik(name) VALUES ('fresh breadcrumb');
INSERT INTO skladnik(name) VALUES ('canola oil');
INSERT INTO skladnik(name) VALUES ('instant vanilla pudding');
INSERT INTO skladnik(name) VALUES ('zucchini');
INSERT INTO skladnik(name) VALUES ('fresh parsley');
INSERT INTO skladnik(name) VALUES ('low-fat buttermilk');
INSERT INTO skladnik(name) VALUES ('sweet corn');
INSERT INTO skladnik(name) VALUES ('rotel tomatoes');
INSERT INTO skladnik(name) VALUES ('cooked chicken');
INSERT INTO skladnik(name) VALUES ('fat');
INSERT INTO skladnik(name) VALUES ('buttermilk');
INSERT INTO skladnik(name) VALUES ('great northern bean');
INSERT INTO skladnik(name) VALUES ('beef');
INSERT INTO skladnik(name) VALUES ('black pepper');
INSERT INTO skladnik(name) VALUES ('scallions');
INSERT INTO skladnik(name) VALUES ('applesauce');
INSERT INTO skladnik(name) VALUES ('sugar-free non-fat vanilla yogurt');
INSERT INTO skladnik(name) VALUES ('jalapeno');
INSERT INTO skladnik(name) VALUES ('dried basil');
INSERT INTO skladnik(name) VALUES ('wood bethony');
INSERT INTO skladnik(name) VALUES ('sliced mushrooms');
INSERT INTO skladnik(name) VALUES ('bacon');
INSERT INTO skladnik(name) VALUES ('fat-free mayonnaise');
INSERT INTO skladnik(name) VALUES ('sage');
INSERT INTO skladnik(name) VALUES ('crushed pineapple');
INSERT INTO skladnik(name) VALUES ('yellow onion');
INSERT INTO skladnik(name) VALUES ('red chili pepper');
INSERT INTO skladnik(name) VALUES ('dry yeast');
INSERT INTO skladnik(name) VALUES ('cookie');
INSERT INTO skladnik(name) VALUES ('crouton');
INSERT INTO skladnik(name) VALUES ('beef stew meat');
INSERT INTO skladnik(name) VALUES ('garlic powder');
INSERT INTO skladnik(name) VALUES ('unflavored gelatin');
INSERT INTO skladnik(name) VALUES ('salted peanuts');
INSERT INTO skladnik(name) VALUES ('beer');
INSERT INTO skladnik(name) VALUES ('lemon');
INSERT INTO skladnik(name) VALUES ('ground cinnamon');
INSERT INTO skladnik(name) VALUES ('oreo cookie crumbs');
INSERT INTO skladnik(name) VALUES ('carrot');
INSERT INTO skladnik(name) VALUES ('albacore tuna in water');
INSERT INTO skladnik(name) VALUES ('condensed cream of chicken soup');
INSERT INTO skladnik(name) VALUES ('extra virgin olive oil');
INSERT INTO skladnik(name) VALUES ('ripe olives');
INSERT INTO skladnik(name) VALUES ('egg yolks');
INSERT INTO skladnik(name) VALUES ('betty crocker fudge brownie mix');
INSERT INTO skladnik(name) VALUES ('white pepper');
INSERT INTO skladnik(name) VALUES ('unsalted butter');
INSERT INTO skladnik(name) VALUES ('fresh lemon juice');
INSERT INTO skladnik(name) VALUES ('paprika');
INSERT INTO skladnik(name) VALUES ('tri-color spiral pasta');
INSERT INTO skladnik(name) VALUES ('lean ground beef');
INSERT INTO skladnik(name) VALUES ('button mushrooms');
INSERT INTO skladnik(name) VALUES ('vinegar');
INSERT INTO skladnik(name) VALUES ('fennel seeds');
INSERT INTO skladnik(name) VALUES ('low-fat sour cream');
INSERT INTO skladnik(name) VALUES ('whole green chilies');
INSERT INTO skladnik(name) VALUES ('dark brown sugar');
INSERT INTO skladnik(name) VALUES ('tomato puree');
INSERT INTO skladnik(name) VALUES ('light olive oil');
INSERT INTO skladnik(name) VALUES ('part-skim ricotta cheese');
INSERT INTO skladnik(name) VALUES ('liquid smoke');
INSERT INTO skladnik(name) VALUES ('whole wheat flour');
INSERT INTO skladnik(name) VALUES ('green olives');
INSERT INTO skladnik(name) VALUES ('ground thyme');
INSERT INTO skladnik(name) VALUES ('dry mustard');
INSERT INTO skladnik(name) VALUES ('buckwheat flour');
INSERT INTO skladnik(name) VALUES ('sliced ripe olives');
INSERT INTO skladnik(name) VALUES ('ground cayenne pepper');
INSERT INTO skladnik(name) VALUES ('fresh corn');
INSERT INTO skladnik(name) VALUES ('taco sauce');
INSERT INTO skladnik(name) VALUES ('grand marnier');
INSERT INTO skladnik(name) VALUES ('sweet pepper');
INSERT INTO skladnik(name) VALUES ('bread');
INSERT INTO skladnik(name) VALUES ('sharp cheddar cheese');
INSERT INTO skladnik(name) VALUES ('apple cider vinegar');
INSERT INTO skladnik(name) VALUES ('orange');
INSERT INTO skladnik(name) VALUES ('juice of');
INSERT INTO skladnik(name) VALUES ('triple sec');
INSERT INTO skladnik(name) VALUES ('bananas');
INSERT INTO skladnik(name) VALUES ('orange juice');
INSERT INTO skladnik(name) VALUES ('vanilla');
INSERT INTO skladnik(name) VALUES ('shortening');
INSERT INTO skladnik(name) VALUES ('fresh cilantro leaves');
INSERT INTO skladnik(name) VALUES ('cloves');
INSERT INTO skladnik(name) VALUES ('white bread');
INSERT INTO skladnik(name) VALUES ('dill pickles');
INSERT INTO skladnik(name) VALUES ('boneless skinless chicken breast');
INSERT INTO skladnik(name) VALUES ('romano cheese');
INSERT INTO skladnik(name) VALUES ('genoa salami');
INSERT INTO skladnik(name) VALUES ('brine');
INSERT INTO skladnik(name) VALUES ('sugar substitute');
INSERT INTO skladnik(name) VALUES ('rind of');
INSERT INTO skladnik(name) VALUES ('cream of mushroom soup');
INSERT INTO skladnik(name) VALUES ('baking cocoa');
INSERT INTO skladnik(name) VALUES ('spinach');
INSERT INTO skladnik(name) VALUES ('black beans');
INSERT INTO skladnik(name) VALUES ('deli turkey');
INSERT INTO skladnik(name) VALUES ('dry white wine');
INSERT INTO skladnik(name) VALUES ('boiling potatoes');
INSERT INTO skladnik(name) VALUES ('italian sausage');
INSERT INTO skladnik(name) VALUES ('yellow onions');
INSERT INTO skladnik(name) VALUES ('carrots');
INSERT INTO skladnik(name) VALUES ('green pepper');
INSERT INTO skladnik(name) VALUES ('cheddar cheese soup');
INSERT INTO skladnik(name) VALUES ('lettuce');
INSERT INTO skladnik(name) VALUES ('fresh basil');
INSERT INTO skladnik(name) VALUES ('swiss cheese');
INSERT INTO skladnik(name) VALUES ('chocolate chips');
INSERT INTO skladnik(name) VALUES ('onion"');
INSERT INTO skladnik(name) VALUES ('mexican seasoning');
INSERT INTO skladnik(name) VALUES ('capers');
INSERT INTO skladnik(name) VALUES ('orange rind');
INSERT INTO skladnik(name) VALUES ('fresh herb');
INSERT INTO skladnik(name) VALUES ('apple pie filling');
INSERT INTO skladnik(name) VALUES ('cabbage');
INSERT INTO skladnik(name) VALUES ('sweetened condensed milk');
INSERT INTO skladnik(name) VALUES ('icing sugar');
INSERT INTO skladnik(name) VALUES ('sausage patty');
INSERT INTO skladnik(name) VALUES ('fresh ginger');
INSERT INTO skladnik(name) VALUES ('beef consomme');
INSERT INTO skladnik(name) VALUES ('cooking oil');
INSERT INTO skladnik(name) VALUES ('parsley');
INSERT INTO skladnik(name) VALUES ('penne pasta');
INSERT INTO skladnik(name) VALUES ('fish');
INSERT INTO skladnik(name) VALUES ('yellow cake mix');
INSERT INTO skladnik(name) VALUES ('frozen peas');
INSERT INTO skladnik(name) VALUES ('potato');
INSERT INTO skladnik(name) VALUES ('ground pork');
INSERT INTO skladnik(name) VALUES ('chopped tomato');
INSERT INTO skladnik(name) VALUES ('squash');
INSERT INTO skladnik(name) VALUES ('poultry seasoning');
INSERT INTO skladnik(name) VALUES ('peanut oil');
INSERT INTO skladnik(name) VALUES ('tomato paste');
INSERT INTO skladnik(name) VALUES ('salmon');
INSERT INTO skladnik(name) VALUES ('fresh spinach leaves');
INSERT INTO skladnik(name) VALUES ('natural-style peanut butter');
INSERT INTO skladnik(name) VALUES ('celery seed');
INSERT INTO skladnik(name) VALUES ('pecans');
INSERT INTO skladnik(name) VALUES ('tequila');
INSERT INTO skladnik(name) VALUES ('boneless chicken breast');
INSERT INTO skladnik(name) VALUES ('butter');
INSERT INTO skladnik(name) VALUES ('soft breadcrumbs');
INSERT INTO skladnik(name) VALUES ('water');
INSERT INTO skladnik(name) VALUES ('hamburger buns');
INSERT INTO skladnik(name) VALUES ('reduced sodium soy sauce');
INSERT INTO skladnik(name) VALUES ('cornmeal');
INSERT INTO skladnik(name) VALUES ('powdered sugar');
INSERT INTO skladnik(name) VALUES ('cottage cheese');
INSERT INTO skladnik(name) VALUES ('ginger');
INSERT INTO skladnik(name) VALUES ('vegetable oil');
INSERT INTO skladnik(name) VALUES ('wax beans');
INSERT INTO skladnik(name) VALUES ('vermicelli');
INSERT INTO skladnik(name) VALUES ('vegetable bouillon cubes');
INSERT INTO skladnik(name) VALUES ('dill weed');
INSERT INTO skladnik(name) VALUES ('breadcrumbs');
INSERT INTO skladnik(name) VALUES ('crushed tomatoes');
INSERT INTO skladnik(name) VALUES ('rolled oats');
INSERT INTO skladnik(name) VALUES ('kalamata olive');
INSERT INTO skladnik(name) VALUES ('apple juice');
INSERT INTO skladnik(name) VALUES ('apple');
INSERT INTO skladnik(name) VALUES ('vegetarian ground beef');
INSERT INTO skladnik(name) VALUES ('dried oregano');
INSERT INTO skladnik(name) VALUES ('sambal oelek');
INSERT INTO skladnik(name) VALUES ('cheddar cheese');
INSERT INTO skladnik(name) VALUES ('yellow bell pepper');
INSERT INTO skladnik(name) VALUES ('whole tomato');
INSERT INTO skladnik(name) VALUES ('sodium-free vegetable broth');
INSERT INTO skladnik(name) VALUES ('soft silken tofu');
INSERT INTO skladnik(name) VALUES ('ham hock');
INSERT INTO skladnik(name) VALUES ('fresh herbs');
INSERT INTO skladnik(name) VALUES ('spices');
INSERT INTO skladnik(name) VALUES ('vanilla instant pudding mix');
INSERT INTO skladnik(name) VALUES ('kidney beans');
INSERT INTO skladnik(name) VALUES ('lemons');
INSERT INTO skladnik(name) VALUES ('prepared pizza crust');
INSERT INTO skladnik(name) VALUES ('stewed tomatoes');
INSERT INTO skladnik(name) VALUES ('monterey jack cheese');
INSERT INTO skladnik(name) VALUES ('lasagna noodle');
INSERT INTO skladnik(name) VALUES ('cilantro');
INSERT INTO skladnik(name) VALUES ('butterscotch chips');
INSERT INTO skladnik(name) VALUES ('fresh cilantro');
INSERT INTO skladnik(name) VALUES ('milk');
INSERT INTO skladnik(name) VALUES ('cornstarch');
INSERT INTO skladnik(name) VALUES ('bean dip');
INSERT INTO skladnik(name) VALUES ('oil');
INSERT INTO skladnik(name) VALUES ('toasted sesame oil');
INSERT INTO skladnik(name) VALUES ('apples');
INSERT INTO skladnik(name) VALUES ('clove');
INSERT INTO skladnik(name) VALUES ('celery');
INSERT INTO skladnik(name) VALUES ('rolls');
INSERT INTO skladnik(name) VALUES ('basil');
INSERT INTO skladnik(name) VALUES ('garlic');
INSERT INTO skladnik(name) VALUES ('broth');
INSERT INTO skladnik(name) VALUES ('rosemary');
INSERT INTO skladnik(name) VALUES ('rubbed sage');
INSERT INTO skladnik(name) VALUES ('sweet onion');
INSERT INTO skladnik(name) VALUES ('peppercorn');
INSERT INTO skladnik(name) VALUES ('thyme');
INSERT INTO skladnik(name) VALUES ('stir fry vegetables');
INSERT INTO skladnik(name) VALUES ('sour cream');
INSERT INTO skladnik(name) VALUES ('frozen vegetables');
INSERT INTO skladnik(name) VALUES ('scallion');
INSERT INTO skladnik(name) VALUES ('dr. pepper cola');
INSERT INTO skladnik(name) VALUES ('raisins');
INSERT INTO skladnik(name) VALUES ('veal roast');
INSERT INTO skladnik(name) VALUES ('sugar');
INSERT INTO skladnik(name) VALUES ('cracked black pepper');
INSERT INTO skladnik(name) VALUES ('miniature semisweet chocolate chips');
INSERT INTO skladnik(name) VALUES ('potatoes');
INSERT INTO skladnik(name) VALUES ('fettuccine pasta');
INSERT INTO skladnik(name) VALUES ('flat leaf parsley');
INSERT INTO skladnik(name) VALUES ('green grape');
INSERT INTO skladnik(name) VALUES ('iceberg lettuce');
INSERT INTO skladnik(name) VALUES ('green beans');
INSERT INTO skladnik(name) VALUES ('white wine vinegar');
INSERT INTO skladnik(name) VALUES ('gelatin');
INSERT INTO skladnik(name) VALUES ('ground cumin');
INSERT INTO skladnik(name) VALUES ('ground cloves');
INSERT INTO skladnik(name) VALUES ('vegetable shortening');
INSERT INTO skladnik(name) VALUES ('cumin');
INSERT INTO skladnik(name) VALUES ('strawberry ice cream');
INSERT INTO skladnik(name) VALUES ('baking soda');
INSERT INTO skladnik(name) VALUES ('chat masala');
INSERT INTO skladnik(name) VALUES ('prepared horseradish');
INSERT INTO skladnik(name) VALUES ('low sodium soy sauce');
INSERT INTO skladnik(name) VALUES ('honey');
INSERT INTO skladnik(name) VALUES ('hot sauce');
INSERT INTO skladnik(name) VALUES ('fresh ground black pepper');
INSERT INTO skladnik(name) VALUES ('egg whites');
INSERT INTO skladnik(name) VALUES ('condensed cream of mushroom soup');
INSERT INTO skladnik(name) VALUES ('chocolate sandwich style cookies');
INSERT INTO skladnik(name) VALUES ('cocoa');
INSERT INTO skladnik(name) VALUES ('dried thyme');
INSERT INTO skladnik(name) VALUES ('cinnamon oil');
INSERT INTO skladnik(name) VALUES ('tomatoes');
INSERT INTO skladnik(name) VALUES ('mayonnaise');
INSERT INTO skladnik(name) VALUES ('egg roll wrap');
INSERT INTO skladnik(name) VALUES ('sorghum');
INSERT INTO skladnik(name) VALUES ('sesame seeds');
INSERT INTO skladnik(name) VALUES ('philadelphia cream cheese');
INSERT INTO skladnik(name) VALUES ('kosher salt');
INSERT INTO skladnik(name) VALUES ('escarole');
INSERT INTO skladnik(name) VALUES ('frozen chopped spinach');
INSERT INTO skladnik(name) VALUES ('mozzarella cheese');
INSERT INTO skladnik(name) VALUES ('vegetable stock');
INSERT INTO skladnik(name) VALUES ('crackers');
INSERT INTO skladnik(name) VALUES ('natural bran');
INSERT INTO skladnik(name) VALUES ('soy sauce');
INSERT INTO skladnik(name) VALUES ('chicken breasts');
INSERT INTO skladnik(name) VALUES ('cream of chicken soup');
INSERT INTO skladnik(name) VALUES ('white onion');
INSERT INTO skladnik(name) VALUES ('italian seasoning');
INSERT INTO skladnik(name) VALUES ('chili-garlic sauce');
INSERT INTO skladnik(name) VALUES ('diced pimentos');
INSERT INTO skladnik(name) VALUES ('low sodium chicken broth');
INSERT INTO skladnik(name) VALUES ('boneless skinless chicken thighs');
INSERT INTO skladnik(name) VALUES ('cream');
INSERT INTO skladnik(name) VALUES ('french bread');
INSERT INTO skladnik(name) VALUES ('toasted wheat germ');
INSERT INTO skladnik(name) VALUES ('red wine vinegar');
INSERT INTO skladnik(name) VALUES ('honey mustard');
INSERT INTO skladnik(name) VALUES ('unsweetened chocolate squares');
INSERT INTO skladnik(name) VALUES ('ham');
INSERT INTO skladnik(name) VALUES ('garbanzo beans');
INSERT INTO skladnik(name) VALUES ('beef steaks');
INSERT INTO skladnik(name) VALUES ('sandwich bun');
INSERT INTO skladnik(name) VALUES ('lime juice');
INSERT INTO skladnik(name) VALUES ('brown sugar');
INSERT INTO skladnik(name) VALUES ('winter squash');
INSERT INTO skladnik(name) VALUES ('red potatoes');
INSERT INTO skladnik(name) VALUES ('ground venison');
INSERT INTO skladnik(name) VALUES ('parmesan cheese');
INSERT INTO skladnik(name) VALUES ('white sugar');
INSERT INTO skladnik(name) VALUES ('gentian root');
INSERT INTO skladnik(name) VALUES ('heavy cream');
INSERT INTO skladnik(name) VALUES ('hass avocado');
INSERT INTO skladnik(name) VALUES ('chicken bouillon cubes');
INSERT INTO skladnik(name) VALUES ('cappelletti pasta');
INSERT INTO skladnik(name) VALUES ('onion powder');
INSERT INTO skladnik(name) VALUES ('all-purpose flour');
INSERT INTO skladnik(name) VALUES ('ketchup');
INSERT INTO skladnik(name) VALUES ('frozen apple juice concentrate');
INSERT INTO skladnik(name) VALUES ('cider vinegar');
INSERT INTO skladnik(name) VALUES ('tempeh');
INSERT INTO skladnik(name) VALUES ('wild mushrooms');
INSERT INTO skladnik(name) VALUES ('white vinegar');
INSERT INTO skladnik(name) VALUES ('parsley flakes');
INSERT INTO skladnik(name) VALUES ('garlic cloves');
INSERT INTO skladnik(name) VALUES ('a.1. original sauce');
INSERT INTO skladnik(name) VALUES ('green onions');
INSERT INTO skladnik(name) VALUES ('prepared graham cracker crusts');
INSERT INTO skladnik(name) VALUES ('plain yogurt');
INSERT INTO skladnik(name) VALUES ('ricotta cheese');
INSERT INTO skladnik(name) VALUES ('beef ribs');
INSERT INTO skladnik(name) VALUES ('rice noodles');
INSERT INTO skladnik(name) VALUES ('mustard powder');
INSERT INTO skladnik(name) VALUES ('dried parsley');
INSERT INTO skladnik(name) VALUES ('prepared yellow mustard');
INSERT INTO skladnik(name) VALUES ('roasted red peppers');
INSERT INTO skladnik(name) VALUES ('cucumber');
INSERT INTO skladnik(name) VALUES ('mixed spice');
INSERT INTO skladnik(name) VALUES ('onions');
INSERT INTO skladnik(name) VALUES ('olive oil');
INSERT INTO skladnik(name) VALUES ('salt free herb and spice seasoning mix');
INSERT INTO skladnik(name) VALUES ('elbow macaroni');
INSERT INTO skladnik(name) VALUES ('diced tomatoes');
INSERT INTO skladnik(name) VALUES ('baking potato');
INSERT INTO skladnik(name) VALUES ('cinnamon sticks');
INSERT INTO skladnik(name) VALUES ('oregano');
INSERT INTO skladnik(name) VALUES ('spreadable cheese with garlic and herbs');
INSERT INTO skladnik(name) VALUES ('coarse salt');
INSERT INTO skladnik(name) VALUES ('red sweet bell peppers');
INSERT INTO skladnik(name) VALUES ('broccoli');
INSERT INTO skladnik(name) VALUES ('eggs');
INSERT INTO skladnik(name) VALUES ('oregano leaves');
INSERT INTO skladnik(name) VALUES ('sweet butter');
INSERT INTO skladnik(name) VALUES ('tomato soup');
INSERT INTO skladnik(name) VALUES ('jiffy corn muffin mix');
INSERT INTO skladnik(name) VALUES ('picante sauce');
INSERT INTO skladnik(name) VALUES ('vanilla extract');
INSERT INTO skladnik(name) VALUES ('plain low-fat yogurt');
INSERT INTO skladnik(name) VALUES ('seasoning salt');
INSERT INTO skladnik(name) VALUES ('bay leaf');
INSERT INTO skladnik(name) VALUES ('dried dill weed');
INSERT INTO skladnik(name) VALUES ('pasta');
INSERT INTO skladnik(name) VALUES ('sesame oil');
INSERT INTO skladnik(name) VALUES ('ground turmeric');
INSERT INTO skladnik(name) VALUES ('yogurt');
INSERT INTO skladnik(name) VALUES ('salt');
INSERT INTO skladnik(name) VALUES ('collard greens');
INSERT INTO skladnik(name) VALUES ('jalapenos');
INSERT INTO skladnik(name) VALUES ('spicy mustard');
INSERT INTO skladnik(name) VALUES ('leaf lettuce');
INSERT INTO skladnik(name) VALUES ('salsa');
INSERT INTO skladnik(name) VALUES ('mirin');
INSERT INTO skladnik(name) VALUES ('vanilla wafers');
INSERT INTO skladnik(name) VALUES ('corn');
INSERT INTO skladnik(name) VALUES ('cornbread');
INSERT INTO skladnik(name) VALUES ('chocolate syrup');
INSERT INTO skladnik(name) VALUES ('unsweetened cocoa powder');
INSERT INTO skladnik(name) VALUES ('hot water');
INSERT INTO skladnik(name) VALUES ('vanilla ice cream');
INSERT INTO skladnik(name) VALUES ('nuts');
INSERT INTO skladnik(name) VALUES ('unsweetened cocoa');
INSERT INTO skladnik(name) VALUES ('toasted sesame seeds');
INSERT INTO skladnik(name) VALUES ('fresh ground pepper');
INSERT INTO skladnik(name) VALUES ('non-fat powdered milk');
INSERT INTO skladnik(name) VALUES ('black olives');
INSERT INTO skladnik(name) VALUES ('olive oil flavored cooking spray');
INSERT INTO skladnik(name) VALUES ('ground beef');
INSERT INTO skladnik(name) VALUES ('cream cheese');
INSERT INTO skladnik(name) VALUES ('prego spaghetti sauce');
INSERT INTO skladnik(name) VALUES ('bittersweet chocolate');
INSERT INTO skladnik(name) VALUES ('dry ranch dressing mix');
INSERT INTO skladnik(name) VALUES ('whole kernel corn');
INSERT INTO skladnik(name) VALUES ('cauliflower');
INSERT INTO skladnik(name) VALUES ('egg substitute');
INSERT INTO skladnik(name) VALUES ('rice wine');
INSERT INTO skladnik(name) VALUES ('margarine');
INSERT INTO skladnik(name) VALUES ('chili powder');
INSERT INTO skladnik(name) VALUES ('tomato juice');
INSERT INTO skladnik(name) VALUES ('orange marmalade');
INSERT INTO skladnik(name) VALUES ('beef broth');
INSERT INTO skladnik(name) VALUES ('pork spareribs');
INSERT INTO skladnik(name) VALUES ('tabasco sauce');
INSERT INTO skladnik(name) VALUES ('cake flour');
INSERT INTO skladnik(name) VALUES ('miniature peppermint patties');
INSERT INTO skladnik(name) VALUES ('toasted almonds');
INSERT INTO skladnik(name) VALUES ('avocado');
INSERT INTO skladnik(name) VALUES ('yam');
INSERT INTO skladnik(name) VALUES ('parsley sprigs');
INSERT INTO skladnik(name) VALUES ('salt and pepper');
INSERT INTO skladnik(name) VALUES ('english cucumber');
INSERT INTO skladnik(name) VALUES ('granulated sugar');
INSERT INTO skladnik(name) VALUES ('broccoli stem');
INSERT INTO skladnik(name) VALUES ('boneless skinless chicken breast halves');
INSERT INTO skladnik(name) VALUES ('ground pepper');
INSERT INTO skladnik(name) VALUES ('molasses');
INSERT INTO skladnik(name) VALUES ('asian chili sauce');
INSERT INTO skladnik(name) VALUES ('whiskey');
INSERT INTO skladnik(name) VALUES ('spearmint');
INSERT INTO skladnik(name) VALUES ('salt & pepper');
INSERT INTO skladnik(name) VALUES ('radish sprouts');
INSERT INTO skladnik(name) VALUES ('walnuts');
INSERT INTO skladnik(name) VALUES ('no-salt-added ketchup');
INSERT INTO skladnik(name) VALUES ('condensed cream of mushroom & garlic soup');
INSERT INTO skladnik(name) VALUES ('chives');
INSERT INTO skladnik(name) VALUES ('american cheese');
INSERT INTO skladnik(name) VALUES ('new potatoes');
INSERT INTO skladnik(name) VALUES ('mushroom pieces');
INSERT INTO skladnik(name) VALUES ('green onion');
INSERT INTO skladnik(name) VALUES ('fresh coarse ground black pepper');
INSERT INTO skladnik(name) VALUES ('roast beef');
INSERT INTO skladnik(name) VALUES ('prepared mustard');
INSERT INTO skladnik(name) VALUES ('green peas');
INSERT INTO skladnik(name) VALUES ('chunky salsa');
INSERT INTO skladnik(name) VALUES ('chicken stock');
INSERT INTO skladnik(name) VALUES ('burnet root');
INSERT INTO skladnik(name) VALUES ('beef bouillon cube');
INSERT INTO skladnik(name) VALUES ('tarragon');
INSERT INTO skladnik(name) VALUES ('red bell pepper');
INSERT INTO skladnik(name) VALUES ('scullcap herb');
INSERT INTO skladnik(name) VALUES ('ground sirloin');
INSERT INTO skladnik(name) VALUES ('worcestershire sauce');
INSERT INTO skladnik(name) VALUES ('semi-sweet chocolate chips');
INSERT INTO skladnik(name) VALUES ('bibb lettuce');
INSERT INTO skladnik(name) VALUES ('rice wine vinegar');
INSERT INTO skladnik(name) VALUES ('boiling water');
INSERT INTO skladnik(name) VALUES ('clove oil');
INSERT INTO skladnik(name) VALUES ('lime wedge');
INSERT INTO skladnik(name) VALUES ('coconut');
INSERT INTO skladnik(name) VALUES ('cornbread mix');
INSERT INTO skladnik(name) VALUES ('ground ginger');
INSERT INTO skladnik(name) VALUES ('brewed espresso');
INSERT INTO skladnik(name) VALUES ('flour');
INSERT INTO skladnik(name) VALUES ('peanuts');
INSERT INTO skladnik(name) VALUES ('mushrooms');
INSERT INTO skladnik(name) VALUES ('cheese');
INSERT INTO skladnik(name) VALUES ('fresh dill');
INSERT INTO skladnik(name) VALUES ('dried breadcrumbs');
INSERT INTO skladnik(name) VALUES ('2% low-fat milk');
INSERT INTO skladnik(name) VALUES ('taco seasoning');
INSERT INTO skladnik(name) VALUES ('pear');
INSERT INTO skladnik(name) VALUES ('sherry wine');
INSERT INTO skladnik(name) VALUES ('provolone cheese');
INSERT INTO skladnik(name) VALUES ('smoked chicken');
INSERT INTO skladnik(name) VALUES ('whipping cream');
INSERT INTO skladnik(name) VALUES ('limeade');
INSERT INTO skladnik(name) VALUES ('pepperoni');
INSERT INTO skladnik(name) VALUES ('hot chili pepper');
INSERT INTO skladnik(name) VALUES ('salt & freshly ground black pepper');
INSERT INTO skladnik(name) VALUES ('shallots');
INSERT INTO skladnik(name) VALUES ('nutmeg');
INSERT INTO skladnik(name) VALUES ('pork loin chops');
INSERT INTO skladnik(name) VALUES ('milk chocolate candy bars');
INSERT INTO skladnik(name) VALUES ('desiccated coconut');
INSERT INTO skladnik(name) VALUES ('mccormicks montreal brand steak seasoning');
INSERT INTO skladnik(name) VALUES ('low sodium beef broth');
INSERT INTO skladnik(name) VALUES ('angel hair pasta');